name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get chinatvnews.m3u8
      run: |
        touch ./twctvnews.m3u8
        sudo cat >./twctvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@twctvnews/live)
        EOL
    - name: Get chinatvnews.m3u8
      run: |
        touch ./chinatvnews.m3u8
        sudo cat >./chinatvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@chinatvnews/live)
        EOL
    - name: Get TTV_NEWS.m3u8
      run: |
        touch ./TTV_NEWS.m3u8
        sudo cat >./TTV_NEWS.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TTV_NEWS/live)
        EOL
    - name: Get FTV_News.m3u8
      run: |
        touch ./FTV_News.m3u8
        sudo cat >./FTV_News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@FTV_News/live)
        EOL
    - name: Get PNNPTS.m3u8
      run: |
        touch ./PNNPTS.m3u8
        sudo cat >./PNNPTS.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@PNNPTS/live)
        EOL
    - name: Get newsebc.m3u8
      run: |
        touch ./newsebc.m3u8
        sudo cat >./newsebc.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@newsebc/live)
        EOL
    - name: Get 57ETFN.m3u8
      run: |
        touch ./57ETFN.m3u8
        sudo cat >./57ETFN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@57ETFN/live)
        EOL
    - name: Get CtiTv.m3u8
      run: |
        touch ./CtiTv.m3u8
        sudo cat >./CtiTv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@CtiTv/live)
        EOL
    - name: Get ctiplusnews.m3u8
      run: |
        touch ./ctiplusnews.m3u8
        sudo cat >./ctiplusnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@ctiplusnews/live)
        EOL
    - name: Get CtiAsia.m3u8
      run: |
        touch ./CtiAsia.m3u8
        sudo cat >./CtiAsia.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@CtiAsia/live)
        EOL
    - name: Get TVBSNEWS01.m3u8
      run: |
        touch ./TVBSNEWS01.m3u8
        sudo cat >./TVBSNEWS01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TVBSNEWS01/live)
        EOL
    - name: Get TVBSNEWS02.m3u8
      run: |
        touch ./TVBSNEWS02.m3u8
        sudo cat >./TVBSNEWS02.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TVBSNEWS02/live)
        EOL
    - name: Get setnews.m3u8
      run: |
        touch ./setnews.m3u8
        sudo cat >./setnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@setnews/live)
        EOL
    - name: Get setinews.m3u8
      run: |
        touch ./setinews.m3u8
        sudo cat >./setinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@setinews/live)
        EOL
    - name: Get globalnewstw.m3u8
      run: |
        touch ./globalnewstw.m3u8
        sudo cat >./globalnewstw.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@globalnewstw/live)
        EOL
    - name: Get mnews-tw.m3u8
      run: |
        touch ./mnews-tw.m3u8
        sudo cat >./mnews-tw.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@mnews-tw/live)
        EOL
    - name: Get DaAiVideo.m3u8
      run: |
        touch ./DaAiVideo.m3u8
        sudo cat >./DaAiVideo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@DaAiVideo/live)
        EOL
    - name: Get DaAiVideo2.m3u8
      run: |
        touch ./DaAiVideo2.m3u8
        sudo cat >./DaAiVideo2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@DaAiVideo2/live)
        EOL
    - name: Get phoenixtvhk.m3u8
      run: |
        touch ./phoenixtvhk.m3u8
        sudo cat >./phoenixtvhk.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@phoenixtvhk/live)
        EOL

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
